language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# Install latest konachan and swp program.
before_install:
  - git submodule init && git submodule update
  - make install_dep

addons:
  apt:
    packages:
      - cmake

# Install swp and konachan dependencies.
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libfreeimage-dev libsdl2-dev libssl-dev libjson0-dev

# Install python dependencies.
install:
  - pip install .
  - python setup.py build
  - python setup.py install
