language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# Install latest konachan and swp program.
before_install:
  - git submodule init && git submodule update 
  - mkdir swp/build && cd swp/build
  - cmake ..
  - cmake --build .
  - ctest -VV
  - mkdir konachan/build && cd konachan/build
  - cmake ..
  - cmake --build .
  - ctest -VV
  - cmake sw

addons:
  apt:
    packages:
      - cmake

# Install dependencies.
install:
  - pip install .
